name:                kek-hbot
version:             0.1.0.0
github:              "githubuser/kek-hbot"
license:             BSD3
author:              "Gregory Kulakov"
maintainer:          "lobster287@gmail.com"
copyright:           "2020 Gregory Kulakov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/GregoryGhost/kek-hbot#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  kek-hbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kek-hbot

tests:
  kek-hbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kek-hbot
