name:                kek-hbot
version:             0.1.0.0
github:              "GregoryGhost/kek-hbot"
license:             BSD3
author:              "Gregory Kulakov"
maintainer:          "lobster287@gmail.com"
copyright:           "2020 Gregory Kulakov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/GregoryGhost/kek-hbot#readme>

default-extensions: OverloadedStrings
                    OverloadedLabels
                    DuplicateRecordFields
                    DeriveGeneric
                    DerivingVia
                    DataKinds
                    TypeSynonymInstances
                    FlexibleInstances
                    TemplateHaskell
                    MultiParamTypeClasses
                    FunctionalDependencies

dependencies:
- base >= 4.7 && < 5
- http-conduit >= 2.3.7.3
- conduit >= 1.3.2
- time >= 1.9.3
- lens >= 4.18.1
- lens-aeson >= 1.1
- deriving-aeson >= 0.2.6
- http-client >= 0.6.4.1
- http-client-tls >= 0.3.5.3
- http-types >= 0.12.3
- conduit-extra >= 1.3.5
- async >= 2.2.2
- aeson >= 1.4.7.1
- aeson-casing >= 0.2.0.0
- aeson-pretty >= 0.8.8
- text <=1.2.4.0
- bytestring <= 0.10.10.0
- mtl <= 2.2.2
- directory <= 1.3.6.0
- core-hbot >= 0.1.0.0
- filepath >= 1.4.2.1
- exceptions >= 0.10.4
- quickcheck-instances <= 0.3.22
- QuickCheck <= 2.13.2

library:
  source-dirs: src

executables:
  kek-hbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kek-hbot

tests:
  kek-hbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kek-hbot
